
name: Build and test
on:
  - push
  # Build if requested manually from the Actions tab
  - workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          default: true
      - name: Check formatting
        run: cargo fmt -- --check

  linting:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          default: true
      - name: Lint (clippy)
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - name: Install cargo-audit
        uses: actions-rs/install@v0.1.2
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true
      - name: Audit
        run: cargo audit --deny warnings


  build-and-test:
    strategy:
      matrix:
        # MSRV. Not considered breaking when this has to be bumped.
        # But should be mentioned in the changelog.
        rust: [stable, beta, nightly, 1.64.0]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          default: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
